import Link from "next/link";
import "./globals.css";
import {Control} from "./Control";
import fs from "node:fs/promises";
import path from "node:path";


export const metadata = {
  title: "Web Tutorials",
  description: "Generated by SuseongJr.",
};

export default async function RootLayout({ children }) {
  let topics = [];
  let errorMessage = null;
  try {
    const dbPath = path.join(process.cwd(), 'db.json');
    const file = await fs.readFile(dbPath, 'utf-8');
    const db = JSON.parse(file);
    topics = Array.isArray(db?.topics) ? db.topics : [];
  } catch (error) {
    errorMessage = error instanceof Error ? error.message : '알 수 없는 오류가 발생했습니다.';
  }
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>

      {errorMessage ? <p style={{color: 'red'}}>데이터 로딩 오류: {errorMessage}</p> : null}
      <ol>
        {topics.map((topic)=>{
          return (<li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>);
        })}
      </ol>
        {children}
        <Control/>
      </body>
    </html>
  );
}
