import Link from "next/link";
import "./globals.css";
import {Control} from "./Control";


export const metadata = {
  title: "Web Tutorials",
  description: "Generated by SuseongJr.",
};

export default async function RootLayout({ children }) {
  const baseUrl = process.env.NEXT_PUBLIC_API_URL;
  let topics = [];
  let errorMessage = null;
  try {
    if (!baseUrl) {
      throw new Error('NEXT_PUBLIC_API_URL 환경변수가 설정되지 않았습니다.');
    }
    const url = new URL('topics', baseUrl).toString();
    const resp = await fetch(url, { cache: 'no-store' });
    if (!resp.ok) {
      throw new Error(`토픽 조회 실패: ${resp.status} ${resp.statusText}`);
    }
    topics = await resp.json();
  } catch (error) {
    errorMessage = error instanceof Error ? error.message : '알 수 없는 오류가 발생했습니다.';
  }
  return (
    <html>
      <body>
      <h1><Link href="/">WEB</Link></h1>

      {errorMessage ? <p style={{color: 'red'}}>데이터 로딩 오류: {errorMessage}</p> : null}
      <ol>
        {topics.map((topic)=>{
          return (<li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>);
        })}
      </ol>
        {children}
        <Control/>
      </body>
    </html>
  );
}
